### ISSUE TITLE
Calendar Event

### ISSUE THREAD

**Issue by Baidu0Big** [spendtopic/SpendTermi-of-Scriptable#1]
Why must need Calendar name?

**Comment by spendtopic** [comment]
This issue will be resolved in beta 2.0. currently, beta 2.0 is being tested and beta 2.1 is being developed.

Can you write java?  We're find a programmer because we don't have programmers.

If you can coding, please DM us and we will introduce the relevant content to you.

If you have any questions after regarding this reply, please contact us. Thank you for your time in reviewing this email.

Best,
SpendTopic
